1208 deploy mint erc20
omisego/ewallet pull request #1216
Opened 2020-11-13 07:01 UTC by okalouti

Issue/Task Number:

# Overview

Describe what your Pull Request is about in a few sentences. This is a global description that should tell people what your PR is all about. Don't go too much into details here.

# Changes

- Change 1
- Change 2
- ...

# Implementation Details

Describe your changes and implementation choices. More details make PRs easier to review.

# Usage

Describe how to test your new feature/bug fix. Step by step so we can quickly give it a try.

# Impact

How can this change be deployed? Any special requirement?

2020-11-16 04:02 UTC, okalouti commented
Added some logic to handle `subunit_to_unit` as a string too since JavaScript `MAX_SAFE_INTEGER` is smaller than 10^16

2020-11-17 08:17 UTC, mederic-p requested changes

2020-11-17 08:17 UTC, mederic-p commented on apps/admin_api/test/admin_api/v1/controllers/blockchain/token_controller_test.exs
> +      assert Token.get(response["data"]["id"]) != nil
Can you add an assert on amount? Also make it a bit bigger number.

2020-11-17 08:17 UTC, mederic-p commented on apps/ewallet/lib/ewallet/gates/token_gate.ex
> +  defp normalize_value(amount) do
can be written with a guard clause at the function level
`defp normalize_value(amount) when is_binary(amount) do .....`
`defp normalize_value(amount) do .....`

2020-11-23 05:06 UTC, mederic-p approved these changes

2020-11-23 05:11 UTC, merged